spring:
  application:
    name: springDemo
  datasource:
    #url: jdbc:db2://localhost:25010/testdb
    url: jdbc:db2://ibmdb2:25010/testdb
    driverClassName: com.ibm.db2.jcc.DB2Driver
    username: db2inst1
    password: passw0rd